// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: cloudattr.proto

package cloudattrpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CloudAttribution_Lookup_FullMethodName      = "/cloudattr.v1.CloudAttribution/Lookup"
	CloudAttribution_BatchLookup_FullMethodName = "/cloudattr.v1.CloudAttribution/BatchLookup"
	CloudAttribution_Version_FullMethodName     = "/cloudattr.v1.CloudAttribution/Version"
)

// CloudAttributionClient is the client API for CloudAttribution service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CloudAttribution resolves IP addresses to the cloud provider, region, and
// services that own them.
type CloudAttributionClient interface {
	// Lookup resolves a single IP.
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResult, error)
	// BatchLookup resolves a stream of IPs, one result per request.
	BatchLookup(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LookupRequest, LookupResult], error)
	// Version returns the build epoch of the loaded database.
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type cloudAttributionClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudAttributionClient(cc grpc.ClientConnInterface) CloudAttributionClient {
	return &cloudAttributionClient{cc}
}

func (c *cloudAttributionClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupResult)
	err := c.cc.Invoke(ctx, CloudAttribution_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudAttributionClient) BatchLookup(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LookupRequest, LookupResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CloudAttribution_ServiceDesc.Streams[0], CloudAttribution_BatchLookup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LookupRequest, LookupResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudAttribution_BatchLookupClient = grpc.BidiStreamingClient[LookupRequest, LookupResult]

func (c *cloudAttributionClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, CloudAttribution_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudAttributionServer is the server API for CloudAttribution service.
// All implementations must embed UnimplementedCloudAttributionServer
// for forward compatibility.
//
// CloudAttribution resolves IP addresses to the cloud provider, region, and
// services that own them.
type CloudAttributionServer interface {
	// Lookup resolves a single IP.
	Lookup(context.Context, *LookupRequest) (*LookupResult, error)
	// BatchLookup resolves a stream of IPs, one result per request.
	BatchLookup(grpc.BidiStreamingServer[LookupRequest, LookupResult]) error
	// Version returns the build epoch of the loaded database.
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedCloudAttributionServer()
}

// UnimplementedCloudAttributionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCloudAttributionServer struct{}

func (UnimplementedCloudAttributionServer) Lookup(context.Context, *LookupRequest) (*LookupResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedCloudAttributionServer) BatchLookup(grpc.BidiStreamingServer[LookupRequest, LookupResult]) error {
	return status.Error(codes.Unimplemented, "method BatchLookup not implemented")
}
func (UnimplementedCloudAttributionServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedCloudAttributionServer) mustEmbedUnimplementedCloudAttributionServer() {}
func (UnimplementedCloudAttributionServer) testEmbeddedByValue()                          {}

// UnsafeCloudAttributionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudAttributionServer will
// result in compilation errors.
type UnsafeCloudAttributionServer interface {
	mustEmbedUnimplementedCloudAttributionServer()
}

func RegisterCloudAttributionServer(s grpc.ServiceRegistrar, srv CloudAttributionServer) {
	// If the following call panics, it indicates UnimplementedCloudAttributionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CloudAttribution_ServiceDesc, srv)
}

func _CloudAttribution_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAttributionServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAttribution_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAttributionServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudAttribution_BatchLookup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CloudAttributionServer).BatchLookup(&grpc.GenericServerStream[LookupRequest, LookupResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CloudAttribution_BatchLookupServer = grpc.BidiStreamingServer[LookupRequest, LookupResult]

func _CloudAttribution_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudAttributionServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudAttribution_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudAttributionServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudAttribution_ServiceDesc is the grpc.ServiceDesc for CloudAttribution service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudAttribution_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudattr.v1.CloudAttribution",
	HandlerType: (*CloudAttributionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _CloudAttribution_Lookup_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _CloudAttribution_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchLookup",
			Handler:       _CloudAttribution_BatchLookup_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cloudattr.proto",
}
