// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: cloudattr.proto

package cloudattrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_cloudattr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudattr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_cloudattr_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// Record is the stable attribution core plus a provider-namespaced ext map.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Services      []string               `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	Ipv6          bool                   `protobuf:"varint,4,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	SyncedAt      int64                  `protobuf:"varint,6,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"` // unix epoch of the feed
	Ext           map[string]string      `protobuf:"bytes,7,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_cloudattr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_cloudattr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_cloudattr_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Record) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Record) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Record) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *Record) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Record) GetSyncedAt() int64 {
	if x != nil {
		return x.SyncedAt
	}
	return 0
}

func (x *Record) GetExt() map[string]string {
	if x != nil {
		return x.Ext
	}
	return nil
}

type LookupResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // non-empty if this IP could not be looked up (e.g. malformed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResult) Reset() {
	*x = LookupResult{}
	mi := &file_cloudattr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResult) ProtoMessage() {}

func (x *LookupResult) ProtoReflect() protoreflect.Message {
	mi := &file_cloudattr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResult.ProtoReflect.Descriptor instead.
func (*LookupResult) Descriptor() ([]byte, []int) {
	return file_cloudattr_proto_rawDescGZIP(), []int{2}
}

func (x *LookupResult) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LookupResult) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *LookupResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_cloudattr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudattr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_cloudattr_proto_rawDescGZIP(), []int{3}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildEpoch    int64                  `protobuf:"varint,1,opt,name=build_epoch,json=buildEpoch,proto3" json:"build_epoch,omitempty"`
	DatabaseType  string                 `protobuf:"bytes,2,opt,name=database_type,json=databaseType,proto3" json:"database_type,omitempty"`
	NodeCount     uint64                 `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_cloudattr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloudattr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_cloudattr_proto_rawDescGZIP(), []int{4}
}

func (x *VersionResponse) GetBuildEpoch() int64 {
	if x != nil {
		return x.BuildEpoch
	}
	return 0
}

func (x *VersionResponse) GetDatabaseType() string {
	if x != nil {
		return x.DatabaseType
	}
	return ""
}

func (x *VersionResponse) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

var File_cloudattr_proto protoreflect.FileDescriptor

const file_cloudattr_proto_rawDesc = "" +
	"\n" +
	"\x0fcloudattr.proto\x12\fcloudattr.v1\"\x1f\n" +
	"\rLookupRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x8a\x02\n" +
	"\x06Record\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bservices\x18\x03 \x03(\tR\bservices\x12\x12\n" +
	"\x04ipv6\x18\x04 \x01(\bR\x04ipv6\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1b\n" +
	"\tsynced_at\x18\x06 \x01(\x03R\bsyncedAt\x12/\n" +
	"\x03ext\x18\a \x03(\v2\x1d.cloudattr.v1.Record.ExtEntryR\x03ext\x1a6\n" +
	"\bExtEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\fLookupResult\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12,\n" +
	"\x06record\x18\x02 \x01(\v2\x14.cloudattr.v1.RecordR\x06record\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x10\n" +
	"\x0eVersionRequest\"v\n" +
	"\x0fVersionResponse\x12\x1f\n" +
	"\vbuild_epoch\x18\x01 \x01(\x03R\n" +
	"buildEpoch\x12#\n" +
	"\rdatabase_type\x18\x02 \x01(\tR\fdatabaseType\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x04R\tnodeCount2\xe9\x01\n" +
	"\x10CloudAttribution\x12A\n" +
	"\x06Lookup\x12\x1b.cloudattr.v1.LookupRequest\x1a\x1a.cloudattr.v1.LookupResult\x12J\n" +
	"\vBatchLookup\x12\x1b.cloudattr.v1.LookupRequest\x1a\x1a.cloudattr.v1.LookupResult(\x010\x01\x12F\n" +
	"\aVersion\x12\x1c.cloudattr.v1.VersionRequest\x1a\x1d.cloudattr.v1.VersionResponseBAZ?github.com/ChrisLundquist/cloudip/proto/cloudattrpb;cloudattrpbb\x06proto3"

var (
	file_cloudattr_proto_rawDescOnce sync.Once
	file_cloudattr_proto_rawDescData []byte
)

func file_cloudattr_proto_rawDescGZIP() []byte {
	file_cloudattr_proto_rawDescOnce.Do(func() {
		file_cloudattr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloudattr_proto_rawDesc), len(file_cloudattr_proto_rawDesc)))
	})
	return file_cloudattr_proto_rawDescData
}

var file_cloudattr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cloudattr_proto_goTypes = []any{
	(*LookupRequest)(nil),   // 0: cloudattr.v1.LookupRequest
	(*Record)(nil),          // 1: cloudattr.v1.Record
	(*LookupResult)(nil),    // 2: cloudattr.v1.LookupResult
	(*VersionRequest)(nil),  // 3: cloudattr.v1.VersionRequest
	(*VersionResponse)(nil), // 4: cloudattr.v1.VersionResponse
	nil,                     // 5: cloudattr.v1.Record.ExtEntry
}
var file_cloudattr_proto_depIdxs = []int32{
	5, // 0: cloudattr.v1.Record.ext:type_name -> cloudattr.v1.Record.ExtEntry
	1, // 1: cloudattr.v1.LookupResult.record:type_name -> cloudattr.v1.Record
	0, // 2: cloudattr.v1.CloudAttribution.Lookup:input_type -> cloudattr.v1.LookupRequest
	0, // 3: cloudattr.v1.CloudAttribution.BatchLookup:input_type -> cloudattr.v1.LookupRequest
	3, // 4: cloudattr.v1.CloudAttribution.Version:input_type -> cloudattr.v1.VersionRequest
	2, // 5: cloudattr.v1.CloudAttribution.Lookup:output_type -> cloudattr.v1.LookupResult
	2, // 6: cloudattr.v1.CloudAttribution.BatchLookup:output_type -> cloudattr.v1.LookupResult
	4, // 7: cloudattr.v1.CloudAttribution.Version:output_type -> cloudattr.v1.VersionResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cloudattr_proto_init() }
func file_cloudattr_proto_init() {
	if File_cloudattr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloudattr_proto_rawDesc), len(file_cloudattr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloudattr_proto_goTypes,
		DependencyIndexes: file_cloudattr_proto_depIdxs,
		MessageInfos:      file_cloudattr_proto_msgTypes,
	}.Build()
	File_cloudattr_proto = out.File
	file_cloudattr_proto_goTypes = nil
	file_cloudattr_proto_depIdxs = nil
}
